<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $table = 'settings';
    protected $fillable = ['id', 'key', 'lang', 'value'];
    protected $casts = [
        'value' => 'array',
        'lang' => 'array'
    ];
    //    protected static function boot()
    //    {
    //        parent::boot(); // TODO: Change the autogenerated stub
    //        self::creating(function ($model) {
    //            $model->lang = serialize($model->lang);
    //            $model->value = serialize($model->value);
    //        });
    //    }
}
